import Navbar from "layouts/navbar";
import Head from "next/head";
import { ChildrenType } from "types";
import styles from "./public-layout.module.scss";

interface PublicLayoutProps extends ChildrenType {
  title?: string;
}
const PublicLayout = ({ title, children }: PublicLayoutProps) => {
  return (
    <main className={styles.root}>
      <Head>
        {title ? <title>{`Insta | ${title}`}</title> : <title>Insta</title>}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
    </main>
  );
};

export default PublicLayout;
