import Navbar from "layouts/navbar";
import Head from "next/head";
import { ChildrenType } from "types";
import styles from "./public-layout.module.scss";

export interface LayoutProps extends ChildrenType {
  title?: string;
  hasNavbar?: boolean;
  isPadded?: boolean;
}
const PublicLayout = ({
  title,
  hasNavbar = false,
  isPadded = false,
  children,
}: LayoutProps) => {
  return (
    <>
      <Head>
        {title ? <title>{`Insta | ${title}`}</title> : <title>Insta</title>}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={isPadded ? styles.root : ""}>
        {hasNavbar && <Navbar />}
        {children}
      </main>
    </>
  );
};

export default PublicLayout;
