import useCurrentUser from "hooks/useCurrentUser";
import Navbar from "layouts/navbar";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { ChildrenType } from "types";
import styles from "./main-layout.module.scss";

export interface LayoutProps extends ChildrenType {
  title?: string;
  hasNavbar?: boolean;
  isPadded?: boolean;
}
const MainLayout = ({
  title,
  hasNavbar = false,
  isPadded = false,
  children,
}: LayoutProps) => {
  const { user } = useCurrentUser();

  const router = useRouter();
  useEffect(() => {
    if (!user) {
      router.push("/auth/signin");
    }
  }, [router, user]);
  return (
    <>
      <Head>
        {title ? <title>{`Insta | ${title}`}</title> : <title>Insta</title>}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={isPadded ? styles.root : ""}>
        {hasNavbar && <Navbar />}
        {user && <h1>meron user</h1>}
        {children}
      </main>
    </>
  );
};

export default MainLayout;
