import useCurrentUser from "hooks/useCurrentUser";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { ChildrenType } from "types";
import styles from "./private-layout.module.scss";

interface PrivateLayoutProps extends ChildrenType {
  title?: string;
}
const PrivateLayout = ({ title, children }: PrivateLayoutProps) => {
  const { user } = useCurrentUser();

  const router = useRouter();
  /* useEffect(() => {
    if (user) {
      router.push("/");
    }
  }, [router, user]); */
  return (
    <main className={styles.root}>
      <Head>
        {title ? <title>{`Insta | ${title}`}</title> : <title>Insta</title>}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>PRIVATE LAYOUT</h1>
      {children}
    </main>
  );
};

export default PrivateLayout;
