import useCurrentUser from "hooks/useCurrentUser";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { ChildrenType } from "types";
import Sidebar from "./components/sidebar";
import styles from "./private-layout.module.scss";

interface PrivateLayoutProps extends ChildrenType {
  title?: string;
}
const PrivateLayout = ({ title, children }: PrivateLayoutProps) => {
  return (
    <main>
      <Head>
        {title ? <title>{`Insta | ${title}`}</title> : <title>Insta</title>}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.root}>
        <div className={styles.sidebar}>
          <Sidebar />
        </div>
        <div className={styles.content}> {children}</div>
        <div className={styles.recommendations}> {children}</div>
      </section>
    </main>
  );
};

export default PrivateLayout;
