import Head from "next/head";
import { ChildrenType } from "types";
import MobileNavigation from "./components/navigation";
import Sidebar from "./components/sidebar";
import styles from "./private-layout.module.scss";
interface PrivateLayoutProps extends ChildrenType {
  title?: string;
}
const PrivateLayout = ({ title, children }: PrivateLayoutProps) => {
  return (
    <>
      <Head>
        {title ? <title>{`Insta | ${title}`}</title> : <title>Insta</title>}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.root}>
        <div className={styles.sidebar}>
          <Sidebar />
        </div>
        <div className={styles.content}>
          <p>Infinite Scroll here</p>
          {children}
          {/* {[1, 2, 3, 4, 5, 6, 7].map((i) => (
            <div key={i} className={styles.item} />
          ))} */}
        </div>
        <MobileNavigation />
      </main>
    </>
  );
};

export default PrivateLayout;
