import Head from "next/head";

interface PageTitleProps {
  title?: string;
}
const PageTitle = ({ title }: PageTitleProps) => {
  return (
    <Head>
      {title ? <title>{`Insta | ${title}`}</title> : <title>Insta</title>}
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default PageTitle;
